CC = gcc
CFLAGS = -Wall -Wextra -g

all: main1 main2 main3 main4 main5

main1:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o

main2:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o

main3:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o

main4:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o

main5:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o
