CC = gcc
CFLAGS = -Wall -Wextra -g

all: main1 main2 main4a main4b

main1:
	$(CC) $(CFLAGS) -lm $@.c -o $@.o
	./$@.o

main2:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o

main3:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o

main4a:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o


main4b:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o

main5:
	$(CC) $(CFLAGS) $@.c -o $@.o
	./$@.o
